version: 0.2

phases:
  build:
    commands:
    - echo "This is build phase... Zipping my lambda function"
    - zip -r deployment_package.zip *
  post_build:
    commands:
    - echo "Deploying to the Lambda..!!"
   
    - aws lambda update-function-code --function-name  myFunction --zip-file fileb://deployment_package.zip
    
    - aws lambda create-function --function-name my-function9 --runtime nodejs14.x --zip-file fileb://deployment_package.zip --handler my-function9.handler --role arn:aws:iam::481195286011:role/service-role/myFunction-role-d63r6lmm
