version: 0.2

phases:
  build:
    commands:
    - echo "This is build phase... Zipping my lambda function"
    - zip -r deployment_package.zip *
  post_build:
    commands:
    - echo "Deploying to the Lambda..!!"
   
    - aws lambda update-function-code --function-name  myFunction --zip-file fileb://deployment_package.zip
    
    - aws lambda create-function --function-name my-function5 --runtime nodejs14.x --zip-file fileb://deployment_package.zip


